name: micad-py310
channels: [conda-forge]
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy
  - statsmodels
  - matplotlib
  - nibabel
  - antspyx
  - openpyxl
  - pip
  - pip:
      - tabulate
